ALTER TABLE characters
  ADD COLUMN IF NOT EXISTS crawler_level INTEGER NOT NULL DEFAULT 1 CHECK (crawler_level > 0),
  ADD COLUMN IF NOT EXISTS crawler_xp INTEGER NOT NULL DEFAULT 0 CHECK (crawler_xp >= 0),
  ADD COLUMN IF NOT EXISTS crawler_stats JSONB NOT NULL DEFAULT '{}'::JSONB;
